import Head from "next/head";
import TodoApp from "../../components/TodoApp";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="" />
      </Head>

      <section className="flex justify-center items-center h-screen">
        <TodoApp/>
      </section>
    </div>
  )
}
